print("Welcome to your adventure simulator. I am going to ask you a bunch of questions and then create an epic story with you as the star!")
print()
userName = input("Enter your name: ")
enemyName = input("Enter your enemy's name: ")
superpower = input("Enter your superpower: ")
live = input("Enter where you live: ")
favouriteFood = input("Enter your favourite food: ")
print()
print("Hello " + userName + "! Your ability to " + superpower + " will make sure you", "\033[31m", "never", "\033[0m", "have to look at " + enemyName + " again. Go eat " + favouriteFood + " as you walk down the streets of " + live + " and use your ability to " + superpower + " for good and not evil!")